-- =================================================================
--  Skema Inventori untuk Aplikasi Peternakan
-- =================================================================
--  Jalankan skrip ini di Supabase SQL Editor Anda.
-- =================================================================

-- Tipe data enum untuk kategori item inventori
create type public.inventory_item_type as enum ('PAKAN', 'VITAMIN', 'OBAT', 'VAKSIN');

-- =================================================================
--  Tabel: inventory_items
--  Menyimpan semua item di dalam inventori beserta stoknya.
-- =================================================================
create table if not exists public.inventory_items (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  item_type public.inventory_item_type not null,
  item_code text, -- Khusus untuk pakan, bisa null untuk yang lain
  name text not null,
  quantity numeric not null default 0,
  unit text not null -- Contoh: 'kg', 'liter', 'pcs', 'botol'
);

-- Menambahkan constraint unik untuk kode pakan
alter table public.inventory_items
add constraint unique_item_code unique (item_code);

-- Mengaktifkan Row Level Security (RLS)
alter table public.inventory_items enable row level security;

-- Kebijakan: Izinkan semua tindakan untuk pengguna anonim (untuk saat ini)
create policy "Allow anon users to manage inventory"
on public.inventory_items for all
to anon
using (true)
with check (true);

-- =================================================================
--  Akhir dari skrip
-- =================================================================