-- Create table to hold different production standards
CREATE TABLE public.production_standards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    breed TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    UNIQUE(company_id, name)
);
COMMENT ON TABLE public.production_standards IS 'Stores different sets of production standards for comparison.';

-- Create table for the actual time-series data of each standard
CREATE TABLE public.production_standard_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    standard_id BIGINT NOT NULL REFERENCES public.production_standards(id) ON DELETE CASCADE,
    age_weeks INT NOT NULL,
    hen_day_production_percent NUMERIC(5, 2),
    cumulative_eggs_per_hen NUMERIC(5, 1),
    egg_weight_g NUMERIC(5, 2),
    daily_feed_intake_g NUMERIC(6, 2),
    body_weight_g NUMERIC(6, 2),
    cumulative_feed_intake_kg NUMERIC(6, 2),
    UNIQUE(standard_id, age_weeks)
);
COMMENT ON TABLE public.production_standard_data IS 'Time-series data points for a specific production standard.';

-- RLS Policies
ALTER TABLE public.production_standards ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view standards in their own company" ON public.production_standards FOR SELECT USING (company_id = get_current_company_id());
CREATE POLICY "Admins can manage standards in their own company" ON public.production_standards FOR ALL USING (company_id = get_current_company_id() AND (SELECT role FROM employees WHERE user_id = auth.uid() AND company_id = get_current_company_id()) = 'Admin');

ALTER TABLE public.production_standard_data ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view standard data from their own company" ON public.production_standard_data FOR SELECT USING (
    (SELECT company_id FROM public.production_standards WHERE id = standard_id) = get_current_company_id()
);
CREATE POLICY "Admins can manage standard data in their own company" ON public.production_standard_data FOR ALL USING (
    (SELECT company_id FROM public.production_standards WHERE id = standard_id) = get_current_company_id() AND (SELECT role FROM employees WHERE user_id = auth.uid() AND company_id = get_current_company_id()) = 'Admin')
WITH CHECK (
    (SELECT company_id FROM public.production_standards WHERE id = standard_id) = get_current_company_id()
);