-- 0019_respiratory_schema.sql

-- Create the table to store respiratory check data
CREATE TABLE public.respiratory_data (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flock_id bigint NOT NULL REFERENCES public.flocks(id) ON DELETE CASCADE,
    organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    check_date date NOT NULL,
    respiratory_score integer NOT NULL CHECK (respiratory_score >= 0 AND respiratory_score <= 5),
    symptoms text[],
    notes text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT unique_respiratory_check UNIQUE (flock_id, check_date)
);

-- Enable RLS
ALTER TABLE public.respiratory_data ENABLE ROW LEVEL SECURITY;

-- Grant access to authenticated users
GRANT SELECT, INSERT, UPDATE, DELETE ON public.respiratory_data TO authenticated;

-- RLS Policies for respiratory_data
CREATE POLICY "Allow full access to own organization data"
ON public.respiratory_data
FOR ALL
USING (organization_id = (SELECT current_organization_id()));

-- Indexes for performance
CREATE INDEX idx_respiratory_data_flock_id ON public.respiratory_data(flock_id);
CREATE INDEX idx_respiratory_data_organization_id ON public.respiratory_data(organization_id);
CREATE INDEX idx_respiratory_data_check_date ON public.respiratory_data(check_date);